### ISSUE TITLE
Unable to use react-app-rewire-typescript

### ISSUE THREAD

**Issue by ratoaq2** [lwd-technology/react-app-rewire-typescript#4]
I'm using latest create-react-app:

```config-overrides.js
const rewireTypescript = require('react-app-rewire-typescript')

module.exports = function override(config, env) {
  config = rewireTypescript(config, env)
  return config
}
```

```output
C:\projects\my-app>npm start

> my-app@0.1.0 start C:\projects\my-app
> react-app-rewired start

C:\projects\my-app\node_modules\react-app-rewire-typescript\index.js:41
  const { index, rules } = findIndexAndRules(rulesSource, ruleMatcher)
                           ^

TypeError: Cannot match against 'undefined' or 'null'.
    at addBeforeRule (C:\projects\my-app\node_modules\react-app-rewire-typescript\index.js:41:28)
    at rewireTypescript (C:\projects\my-app\node_modules\react-app-rewire-typescript\index.js:87:3)
    at override (C:\projects\my-app\config-overrides.js:22:12)
    at Object.<anonymous> (C:\projects\my-app\node_modules\react-app-rewired\scripts\start.js:16:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by barbalex** [comment]
Very similar error here:

```bash
yarn start
yarn run v1.3.2
$ react-app-rewired start
C:\Users\alex\apf2\node_modules\react-app-rewire-typescript\index.js:41
  const { index, rules } = findIndexAndRules(rulesSource, ruleMatcher)
          ^

TypeError: Cannot destructure property `index` of 'undefined' or 'null'.
    at addBeforeRule (C:\Users\alex\apf2\node_modules\react-app-rewire-typescript\index.js:41:28)
    at rewireTypescript (C:\Users\alex\apf2\node_modules\react-app-rewire-typescript\index.js:87:3)
    at override (C:\Users\alex\apf2\config-overrides.js:5:12)
    at Object.<anonymous> (C:\Users\alex\apf2\node_modules\react-app-rewired\scripts\start.js:16:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Environment:

- windows 10
- node 8.9.0
- npm 5.5.1
- react-scripts: 1.0.17

**Comment by TabrisK** [comment]
The same problem
